version: "2.4"

services:
  odoo_proxy:
    image: tecnativa/whitelist
    depends_on:
      - odoo
    networks: &public
      default:
      public:
    ports:
      - "14899:6899"
      - "14069:8069"
    environment:
      PORT: "6899 8069"
      TARGET: odoo

  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
    volumes:
      - ./odoo/custom/conf.d:/opt/odoo/custom/conf.d:ro,z
      - ./odoo/custom/src/private:/opt/odoo/custom/src/private:ro,z
      - ./odoo/custom/src/addons.yaml:/opt/odoo/custom/src/addons.yaml:ro,z
      - ./odoo/custom/src/repos.yaml:/opt/odoo/custom/src/repos.yaml:ro,z
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "128.199.253.126"
      traefik.enable: "true"
      traefik.domain: "128.199.253.126"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:128.199.253.126;Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule: Host:128.199.253.126
      traefik.longpolling-0.frontend.rule: Host:128.199.253.126;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.faf-14-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.faf-14-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.faf-14-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.faf-14-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.faf-14-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.services.faf-14-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.faf-14-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.faf-14-0-prod-main-0.rule: Host(`128.199.253.126`)
      traefik.http.routers.faf-14-0-prod-main-0.service: faf-14-0-prod-main
      traefik.http.routers.faf-14-0-prod-main-0.middlewares:
        faf-14-0-prod-buffering, faf-14-0-prod-compress
      traefik.http.routers.faf-14-0-prod-longpolling-0.rule:
        Host(`128.199.253.126`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.faf-14-0-prod-longpolling-0.service: faf-14-0-prod-longpolling
      traefik.http.routers.faf-14-0-prod-forbiddenCrawlers-0.rule:
        Host(`128.199.253.126`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.faf-14-0-prod-forbiddenCrawlers-0.service: faf-14-0-prod-main
      traefik.http.routers.faf-14-0-prod-forbiddenCrawlers-0.middlewares:
        faf-14-0-prod-buffering, faf-14-0-prod-compress, faf-14-0-prod-forbid-crawlers

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1
  public:

volumes:
  filestore:
  db:
