version: "2.4"

services:
  odoo_proxy:
    image: tecnativa/whitelist
    depends_on:
      - odoo
    networks: &public
      default:
      public:
    ports:
      - "14899:6899"
      - "14069:8069"
    environment:
      PORT: "6899 8069"
      TARGET: odoo

  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
    volumes:
      - ./odoo/custom/conf.d:/opt/odoo/custom/conf.d:ro,z
      - ./odoo/custom/src/private:/opt/odoo/custom/src/private:ro,z
      - ./odoo/custom/src/addons.yaml:/opt/odoo/custom/src/addons.yaml:ro,z
      - ./odoo/custom/src/repos.yaml:/opt/odoo/custom/src/repos.yaml:ro,z
    depends_on:
      - db
    networks:
      default:
    labels:
      doodba.domain.main: ""

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1
  public:

volumes:
  filestore:
  db:
